package net.yzsaas.mail.cloudmailnative.cloudmailnative.copytext.CloudMailNative.copyText

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsCopyTextMethodIDL : AbsSparklingIDLMethod<AbsCopyTextMethodIDL.IDLMethodCopyTextInputModel, AbsCopyTextMethodIDL.IDLMethodCopyTextResultModel>() {

    @IDLMethodName(name = "CloudMailNative.copyText", params = ["text"], results = ["success", "message"])
    final override val name: String = "CloudMailNative.copyText"

    @IDLMethodParamModel
    interface IDLMethodCopyTextInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "text")
        val text: String 
    }

    @IDLMethodResultModel
    interface IDLMethodCopyTextResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean? 

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "message")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "message")
        var message: String? 
    }
}
