package net.yzsaas.mail.cloudmailnative.cloudmailnative.pickfiles.CloudMailNative.pickFiles

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsPickFilesMethodIDL : AbsSparklingIDLMethod<AbsPickFilesMethodIDL.IDLMethodPickFilesInputModel, AbsPickFilesMethodIDL.IDLMethodPickFilesResultModel>() {

    @IDLMethodName(name = "CloudMailNative.pickFiles", params = ["maxCount"], results = ["files"])
    final override val name: String = "CloudMailNative.pickFiles"

    @IDLMethodParamModel
    interface IDLMethodPickFilesInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "maxCount", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 6))
        val maxCount: Number 
    }

    @IDLMethodResultModel
    interface IDLMethodPickFilesResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "files", nestedClassType = PickedFile::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "files", nestedClassType = PickedFile::class)
        var files: List<PickedFile>? 
    }
}
